# Generated by Django 5.0.3 on 2024-05-11 13:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("customer", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
                ("products", models.JSONField(default=list)),
                ("payment", models.CharField(default="COD", max_length=250)),
                ("status", models.CharField(default="Unpaid", max_length=100)),
                ("address", models.CharField(default="None", max_length=250)),
                ("amount", models.CharField(default="100", max_length=100)),
            ],
        ),
    ]
