# Generated by Django 5.0.3 on 2024-05-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("Unpaid", "Unpaid"), ("Paid", "Paid")],
                default="Unpaid",
                max_length=100,
            ),
        ),
    ]
