# Generated by Django 5.0.3 on 2024-04-18 14:31

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_products_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="cat_image",
            field=models.ImageField(
                default="items/default.jpeg", upload_to=products.models.upload_to
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.ImageField(
                default="items/default.jpeg", upload_to=products.models.upload_to
            ),
        ),
    ]
