# Generated by Django 5.0.3 on 2024-04-09 03:25

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='items/default.jpeg', upload_to=products.models.upload_to),
        ),
    ]
