# Generated by Django 5.0.3 on 2024-05-11 13:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_category_cat_image_alter_products_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="products",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
    ]
