# Generated by Django 5.0.3 on 2024-05-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products_api", "0002_delete_items_order_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment",
            field=models.CharField(default="COD", max_length=250),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(default="Unpaid", max_length=100),
        ),
    ]
