# Generated by Django 5.0.3 on 2024-05-06 14:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products_api", "0003_order_payment_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
