# Generated by Django 5.0.3 on 2024-05-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products_api", "0004_alter_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.CharField(default="None", max_length=250),
        ),
        migrations.AddField(
            model_name="order",
            name="amount",
            field=models.CharField(default="100", max_length=100),
        ),
    ]
